baseURL = "https://alejandrodiaz.eu/"
languageCode = "es-es"
title = "Alejandro DÃ­az"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  author = "Alejandro DÃ­az"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true

  [params.homeInfoParams]
    Title = "Hola ðŸ‘‹"
    Content = "Soy un profesional TIC apasionado por la innovaciÃ³n, las redes IT y la inteligencia artificial. AquÃ­ puedes conocerme mejor."

[[menu.main]]
  name = "Sobre mÃ­"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Proyectos"
  url = "/projects/"
  weight = 2

[[menu.main]]
  name = "Contacto"
  url = "/contact/"
  weight = 3

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 4