baseURL = "https://alejandrodiaz.eu/"
languageCode = "es-es"
title = "Alejandro D√≠az"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  author = "Alejandro D√≠az"
  # ‚Ä¶otros par√°metros‚Ä¶
  ShowPostNavLinks = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = true
  ShowToc = true

  [params.homeInfoParams]
    Title = "Hola üëã"
    Content = "Soy un profesional TIC apasionado por la innovaci√≥n, las redes IT y la inteligencia artificial. Aqu√≠ puedes conocerme mejor."

  [params.assets]
    disableFingerprinting = true

  [params.featuredImage]
    previewOnly = false

  [params.list]
  showFeaturedImage = true

[[menu.main]]
  name = "Sobre m√≠"
  url = "/about/"
  weight = 1

[[menu.main]]
  name = "Proyectos"
  url = "/projects/"
  weight = 2

[[menu.main]]
  name = "Contacto"
  url = "/contact/"
  weight = 3

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 4

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/alejandro-dch/"

[[params.socialIcons]]
  name = "email"
  url = "mailto:alexdiaz17490@gmail.com"

[[params.socialIcons]]
  name = "twitter"
  url = "https://x.com/adch17490"

[[params.socialIcons]]
  name = "facebook"
  url = "https://www.facebook.com/alexdiaz17490/"

[[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/adch17490/"

[[params.socialIcons]]
  name = "whatsapp"
  url = "https://wa.me/34615227582"

[[params.socialIcons]]
  name = "telegram"
  url = "https://t.me/stsea90"
